import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");
export const FRAME_W = width * 0.9;
export const FRAME_H = height * 0.9;
export const PHOTO_H = FRAME_H * 0.68;

export const fr = StyleSheet.create({
  outerFrame: {
    position: "absolute",
    top: (height - FRAME_H) / 2,
    left: (width - FRAME_W) / 2,
    width: FRAME_W,
    height: FRAME_H,
    backgroundColor: "#f5f0e8",
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 0,
    elevation: 10,
  },
  topBar: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
    marginBottom: 4,
  },
  snapWrap: { flex: 1 },
  snapText: {
    fontFamily: "mainfont",
    fontSize: 15,
    color: "#1a1a1a",
    letterSpacing: 0.3,
    opacity: 0.72,
  },
  coordsWrap: { alignItems: "flex-end" },
  coordsLabel: {
    fontFamily: "mainfont",
    fontSize: 7,
    color: "rgba(26,26,26,0.4)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  coordsText: {
    fontFamily: "mainfont",
    fontSize: 15,
    color: "rgba(26,26,26,0.65)",
    letterSpacing: 0.5,
    marginTop: 1,
  },
  photoArea: {
    width: "100%",
    height: PHOTO_H - 52,
    backgroundColor: "#0d0c0a",
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    fontFamily: "mainfont",
    fontSize: 52,
    color: "#f0f0ec",
    letterSpacing: 2,
    textShadowColor: "#000",
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 0,
  },
  routeRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 6,
    gap: 6,
  },
  pin: { alignItems: "center", width: 20 },
  pinHead: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#1a1a1a",
    alignItems: "center",
    justifyContent: "center",
  },
  pinDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: "#f5f0e8",
  },
  pinTail: {
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 8,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: "#1a1a1a",
    marginTop: -1,
  },
  dashTrack: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 28,
    overflow: "hidden",
  },
  dash: {
    width: 6,
    height: 2.5,
    backgroundColor: "#1a1a1a",
    borderRadius: 2,
    opacity: 0.5,
  },
  captionStrip: { flex: 1, justifyContent: "center", paddingTop: 10 },
  btnRow: { flexDirection: "row", gap: 16 },
  btn: {
    flex: 1,
    backgroundColor: "#1a1a1a",
    paddingVertical: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 4,
  },
  btnText: {
    fontFamily: "mainfont",
    fontSize: 16,
    color: "#f5f0e8",
    letterSpacing: 1.5,
  },
  btnOutline: {
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: "#1a1a1a",
  },
  btnTextOutline: { color: "#1a1a1a" },
  toggleRow: {
    flexDirection: "row",
    backgroundColor: "#e8e3d8",
    padding: 3,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 0,
  },
  toggleOpt: { flex: 1, paddingVertical: 8, alignItems: "center" },
  toggleActive: {
    backgroundColor: "#1a1a1a",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 3,
  },
  toggleTextActive: {
    color: "#f5f0e8",
    fontFamily: "DMMono-Regular",
    fontSize: 13,
    letterSpacing: 1.2,
  },
  toggleTextInactive: {
    color: "#1a1a1a",
    fontFamily: "DMMono-Regular",
    fontSize: 13,
    letterSpacing: 1.2,
    opacity: 0.4,
  },
  fieldLabel: {
    fontFamily: "DMMono-Regular",
    fontSize: 9,
    color: "#5a5550",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  inp: {
    backgroundColor: "#f0ebe0",
    borderWidth: 1,
    borderColor: "rgba(58,56,48,0.25)",
    borderRadius: 0,
    padding: 10,
    fontFamily: "DMMono-Regular",
    fontSize: 13,
    color: "#1a1a1a",
    marginBottom: 10,
  },
  submitBtn: {
    backgroundColor: "#f4a97f",
    paddingVertical: 11,
    alignItems: "center",
    marginTop: 4,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 0,
    elevation: 4,
  },
  submitBtnText: {
    fontFamily: "DMMono-Medium",
    fontSize: 13,
    color: "#7a3a10",
    letterSpacing: 0.4,
  },
  linkText: {
    fontFamily: "DMMono-Regular",
    fontSize: 11,
    color: "#a08060",
    textAlign: "center",
    marginTop: 6,
    textDecorationLine: "underline",
  },
  errorText: {
    textAlign: "center",
    marginTop: 6,
    color: "#CC3A2A",
    fontSize: 12,
    fontFamily: "DMMono-Regular",
  },
});
