import { StyleSheet } from "react-native";

export const BottomSheet = StyleSheet.create({
  sheetBg: { backgroundColor: "rgba(255, 252, 245, 0.95)" },
  sheetHandle: { backgroundColor: "#3a3830", width: 40 },
  container: { paddingHorizontal: 16, paddingBottom: 40 },

  // ── user card ──
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 14,
    // backgroundColor: '#f9e5d3',
    borderRadius: 14,
    marginBottom: 16,
    marginTop: 8,
    borderWidth: 0.5,
    borderColor: "rgba(255, 255, 255, 0.67)",
  },
  currentTripBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 4,
  },
  currentTripLabel: {
    fontSize: 9,
    color: "#4caf50",
    fontFamily: "DMMono",
    letterSpacing: 1.5,
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#3a3830",
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#f0f0ec",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEditText: { fontSize: 9, color: "#1a1a1a" },
  userInfo: { flex: 1, gap: 2 },
  displayName: { fontSize: 15, color: "#000000", fontFamily: "DMMono" },
  displaySub: {
    fontSize: 10,
    color: "#5a5550",
    fontFamily: "DMMono",
    fontStyle: "italic",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#2a2826",
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtnPrimary: { backgroundColor: "#f0f0ec", borderColor: "transparent" },
  iconBtnText: { fontSize: 16, color: "#888" },
  iconBtnTextPrimary: { fontSize: 20, color: "#1a1a1a" },
  loadingText: { fontSize: 9, color: "#5a5550", fontFamily: "DMMono" },

  // ── title ──
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  titleBlock: { flex: 1 },
  tripName: {
    fontSize: 22,
    color: "#000000",
    fontFamily: "DMMono",
    marginBottom: 4,
  },
  statusRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4caf50",
  },
  statusText: {
    fontSize: 12,
    color: "#a08060",
    fontFamily: "DMMono",
    fontStyle: "italic",
  },
  upBtn: {
    fontSize: 10,
    fontWeight: "700",
    color: "#000000",
    fontFamily: "DMMono",
    letterSpacing: 0.08,
  },
  endTripCover: {
    backgroundColor: "#c03030",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignItems: "center",
    marginVertical: 4,
    minWidth: 70,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 0,
    elevation: 3,
  },
  upBtnText: { color: "#fff", fontSize: 16 },

  // ── stats ──
  statsRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
  statCard: { flex: 1, borderRadius: 12, borderWidth: 0.5, padding: 10 },
  statEmoji: { fontSize: 18, marginBottom: 4 },
  statLabel: {
    fontSize: 10,
    marginBottom: 2,
    fontFamily: "DMMono",
    letterSpacing: 0.4,
  },
  statValue: { fontSize: 22, color: "#3a2a18", fontFamily: "DMMono" },

  // ── divider ──
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  dividerLine: { flex: 1, height: 0.5, backgroundColor: "#3a3830" },
  dividerLabel: {
    fontSize: 9,
    color: "#5a5550",
    fontFamily: "DMMono",
    letterSpacing: 2,
  },

  // ── memories ──
  memoriesScroll: { paddingBottom: 8, gap: 10 },
  memCard: {
    width: 110,
    backgroundColor: "#242220",
    borderRadius: 8,
    paddingTop: 6,
    paddingHorizontal: 6,
    paddingBottom: 22,
  },
  memCardFaded: { opacity: 0.45 },
  memThumb: { width: "100%", height: 70, borderRadius: 6, marginBottom: 6 },
  memLabel: {
    fontSize: 10,
    color: "#f0f0ec",
    fontFamily: "DMMono",
    fontStyle: "italic",
    marginBottom: 2,
  },
  memSub: { fontSize: 9, color: "#5a5550", fontFamily: "DMMono" },
  image: {
    width: "14%",
    height: "100%",
    borderRadius: 10,
    marginRight: 10,
    marginBottom: 10,

    backgroundColor: "#242220",
  },
  tripNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  moreBtn: {
    paddingHorizontal: 4,
  },
  moreBtnText: {
    fontSize: 16,
    color: "#3a3830",
    letterSpacing: 2,
  },
