import { useEffect, useState } from "react";
import TripTimeline from "./timeline";

import { ContentCard } from "../../../../../types/content_card.types";
import CurrentDisplayContentsObserver from "../../../observers/current_contents/current_display_contents_observer";

const MOCK_CONTENT_CARDS: ContentCard[] = [
  {
    uuid: "a1b2c3d4-0001",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/tokyo1/400/600",
    time_stamp: 1718000000000,
    media_id: "media-0001",
    event: "add",
    altitude: 40,
    latitude: 35.6762,
    longitude: 139.6503,
    speed: 0,
    heading: 0,
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    iso_country_code: "JP",
  },
  {
    uuid: "a1b2c3d4-0002",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/tokyo2/300/500",
    time_stamp: 1718003600000,
    media_id: "media-0002",
    event: "add",
    altitude: 38,
    latitude: 35.6814,
    longitude: 139.767,
    speed: 12,
    heading: 45,
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    iso_country_code: "JP",
  },
  {
    uuid: "a1b2c3d4-0003",
    trip_id: "trip-bx-001",
    media_type: "video",
    media_path: "https://picsum.photos/seed/tokyo3/500/400",
    time_stamp: 1718007200000,
    media_id: "media-0003",
    event: "add",
    altitude: 42,
    latitude: 35.6585,
    longitude: 139.7454,
    speed: 8,
    heading: 90,
    city: "Tokyo",
    region: "Tokyo",
    country: "Japan",
    iso_country_code: "JP",
  },
  {
    uuid: "a1b2c3d4-0004",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/paris1/400/500",
    time_stamp: 1718100000000,
    media_id: "media-0004",
    event: "add",
    altitude: 35,
    latitude: 48.8566,
    longitude: 2.3522,
    speed: 0,
    heading: 0,
    city: "Paris",
    region: "Île-de-France",
    country: "France",
    iso_country_code: "FR",
  },
  {
    uuid: "a1b2c3d4-0005",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/paris2/350/500",
    time_stamp: 1718103600000,
    media_id: "media-0005",
    event: "add",
    altitude: 33,
    latitude: 48.8738,
    longitude: 2.295,
    speed: 5,
    heading: 270,
    city: "Paris",
    region: "Île-de-France",
    country: "France",
    iso_country_code: "FR",
  },
  {
    uuid: "a1b2c3d4-0006",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/nyc1/400/400",
    time_stamp: 1718200000000,
    media_id: "media-0006",
    event: "add",
    altitude: 10,
    latitude: 40.7128,
    longitude: -74.006,
    speed: 0,
    heading: 0,
    city: "New York",
    region: "New York",
    country: "United States",
    iso_country_code: "US",
  },
  {
    uuid: "a1b2c3d4-0007",
    trip_id: "trip-bx-001",
    media_type: "video",
    media_path: "https://picsum.photos/seed/nyc2/500/500",
    time_stamp: 1718203600000,
    media_id: "media-0007",
    event: "add",
    altitude: 12,
    latitude: 40.758,
    longitude: -73.9855,
    speed: 20,
    heading: 180,
    city: "New York",
    region: "New York",
    country: "United States",
    iso_country_code: "US",
  },
  {
    uuid: "a1b2c3d4-0008",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/nyc3/300/400",
    time_stamp: 1718207200000,
    media_id: "media-0008",
    event: "add",
    altitude: 15,
    latitude: 40.6892,
    longitude: -74.0445,
    speed: 0,
    heading: 0,
    city: "New York",
    region: "New York",
    country: "United States",
    iso_country_code: "US",
  },
  {
    uuid: "a1b2c3d4-0009",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/sydney1/500/350",
    time_stamp: 1718300000000,
    media_id: "media-0009",
    event: "add",
    altitude: 5,
    latitude: -33.8688,
    longitude: 151.2093,
    speed: 0,
    heading: 0,
    city: "Sydney",
    region: "New South Wales",
    country: "Australia",
    iso_country_code: "AU",
  },
  {
    uuid: "a1b2c3d4-0010",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/sydney2/400/600",
    time_stamp: 1718303600000,
    media_id: "media-0010",
    event: "add",
    altitude: 8,
    latitude: -33.8568,
    longitude: 151.2153,
    speed: 10,
    heading: 135,
    city: "Sydney",
    region: "New South Wales",
    country: "Australia",
    iso_country_code: "AU",
  },
  {
    uuid: "a1b2c3d4-0011",
    trip_id: "trip-bx-001",
    media_type: "video",
    media_path: "https://picsum.photos/seed/hanoi1/450/500",
    time_stamp: 1718400000000,
    media_id: "media-0011",
    event: "add",
    altitude: 20,
    latitude: 21.0285,
    longitude: 105.8542,
    speed: 15,
    heading: 60,
    city: "Hanoi",
    region: "Hanoi",
    country: "Vietnam",
    iso_country_code: "VN",
  },
  {
    uuid: "a1b2c3d4-0012",
    trip_id: "trip-bx-001",
    media_type: "image",
    media_path: "https://picsum.photos/seed/hanoi2/400/500",
    time_stamp: 1718403600000,
    media_id: "media-0012",
    event: "add",
    altitude: 18,
    latitude: 21.034,
    longitude: 105.8412,
    speed: 0,
    heading: 0,
    city: "Hanoi",
    region: "Hanoi",
    country: "Vietnam",
    iso_country_code: "VN",
  },
];

const TimeLineManager = ({ trip_id }) => {
  const initialContents = CurrentDisplayContentsObserver.getAssetArray(trip_id);
  const contentKey = CurrentDisplayContentsObserver.GENERATE_KEY(trip_id);
  const [isTimeLine, setIsTimeLine] = useState<boolean>(false);
  const [isInsert, setIsInsert] = useState(false);
  const [contents, setContents] = useState<ContentCard[]>(initialContents);

  // observer for new contents
  useEffect(() => {
    const updateContents = {
      update(newContents: Array<ContentCard>) {
        setContents(newContents);
      },
    };
    CurrentDisplayContentsObserver.attach(updateContents, contentKey);
  }, []);
  const addContentHandler = (index) => {
    setIsInsert(true);
    console.log(index);
  };
  return (
    <TripTimeline
      cards={contents}
      onAddPress={addContentHandler}
    ></TripTimeline>
  );
};

export default TimeLineManager;
