import { StyleSheet } from "react-native";
export const tripCardsStyle = StyleSheet.create({
  row: {
    justifyContent: "space-between",
    paddingHorizontal: 12,
    marginBottom: 16,
  },
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    width: "80%",
    backgroundColor: "#1a1917",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2e2c29",
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 0,
    elevation: 10,
  },
  warning: {
    fontSize: 32,
    marginBottom: 12,
  },
  title: {
    fontFamily: "DMMono",
    fontSize: 16,
    color: "#f0f0ec",
    marginBottom: 10,
  },
  body: {
    fontFamily: "DMMono",
    fontSize: 11,
    color: "#6b6860",
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 24,
  },
  btnRow: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  btn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 0,
    elevation: 4,
  },
  btnNo: {
    backgroundColor: "#2a2826",
    borderColor: "#3a3835",
  },
  btnNoText: {
    fontFamily: "DMMono",
    fontSize: 13,
    color: "#a09e99",
  },
  btnYes: {
    backgroundColor: "#c03030",
    borderColor: "#8a2020",
  },
  btnYesText: {
    fontFamily: "DMMono",
    fontSize: 13,
    color: "#fff",
  },
  tripCard: {
    width: "48%", // 2 per row
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#111",
  },
  tripImageView: {
    width: "100%",
    height: 170,
  },
  tripImage: {
    width: "100%",
    height: 140,
  },

  tripTitle: {
    paddingVertical: 8,
    textAlign: "center",
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  tripCardMenu: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  tripCardDelete: {
    position: "absolute",
    bottom: 10,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  sharedCardMenu: {
    position: "absolute",
    top: 8,
    left: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },

  tripCardMenuText: {
    color: "#fff",
    fontSize: 14,
    letterSpacing: 1,
    lineHeight: 14,
  },
});
